

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    volumes:
      - MD:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    env_file:
      - .env
    networks:
      ConNet:
        ipv4_address: 10.10.10.4

  nodejs:
    build: ./requirements/nodejs
    container_name: nodejs
    image: nodejs
    depends_on:
      - mariadb
    volumes:
      - NJ:/home/app
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      ConNet:
        ipv4_address: 10.10.10.3


  redis:
    build: ./requirements/redis
    container_name: redis
    image: redis
    volumes:
      - RDS:/var/lib/redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      ConNet:
        ipv4_address: 10.10.10.5
networks:
  ConNet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.0.0/16
         gateway: 10.10.0.1

volumes:
  NJ:
    driver_opts:
      type: none
      o: bind
      device: /home/youssef/data/NJ
  MD:
    driver_opts:
      type: none
      o: bind
      device: /home/youssef/data/MD
  RDS:
    driver_opts:
      type: none
      o: bind
      device: /home/youssef/data/RDS