#!/bin/bash

service mariadb start

mariadb -u root -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DBNAME; \
CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD'; \
GRANT ALL PRIVILEGES ON $MYSQL_DBNAME.* TO '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD'; \
FLUSH PRIVILEGES;"

mariadb -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD'; FLUSH PRIVILEGES;"

mariadb -u root -p$MYSQL_ROOT_PASSWORD < /usr/local/bin/init.sql

mariadb -u root -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DBNAME; \
CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD'; \
GRANT ALL PRIVILEGES ON $MYSQL_DBNAME.* TO '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD'; \
FLUSH PRIVILEGES;"

mariadb -u root -p$MYSQL_ROOT_PASSWORD -e "
GRANT ALL PRIVILEGES ON users_db.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';\
GRANT ALL PRIVILEGES ON files_db.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';\
FLUSH PRIVILEGES;"

mariadb -u root -p$MYSQL_ROOT_PASSWORD -e "SHUTDOWN;"

mariadbd